[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Kade-Powell <kadepowell@gmail.com>"]
description = ""
name = "test-python-dir"
readme = "README.md"
version = "0.1.42"

[tool.poetry.dependencies]
python = "^3.12"
